### PR TITLE
test url failover

### LINKED ISSUE #17: Add tests for URL failover
ethers-ccip-read-provider should have tests for correct handling of multiple URLs where one fails - either with an HTTP-layer error or a non-200 status code.

### PR DESCRIPTION
**Pull request by mdtanrikulu**
resolves #17

One change is, currently [sendRPC function](https://github.com/smartcontractkit/ccip-read/blob/4c323618cfa42d3740e8b348225e0dbf45d786fe/packages/ethers-ccip-read-provider/src/index.ts#L109) throws an error if response status code is in between 400 and 499. If there is a case such as; an information may be available in one server but not in another, we better raise a warning and continue with the next URL instead.

### CODE REVIEW

File: packages/ethers-ccip-read-provider/src/index.ts [hunk 1]
```diff
@@ -106,7 +106,7 @@ async function sendRPC(fetcher: Fetch, urls: string[], to: BytesLike, callData:
     const url = template.replace(/\{([^}]*)\}/g, (_match, p1: keyof typeof args) => args[p1]);
     const data = await fetcher(url, template.includes('{data}') ? undefined : JSON.stringify(args), processFunc);
     if (data.status >= 400 && data.status <= 499) {
-      return logger.throwError('bad response', Logger.errors.SERVER_ERROR, {
+      logger.warn('Bad response', Logger.errors.SERVER_ERROR, {
```
Comment (Arachnid) [inline packages/ethers-ccip-read-provider/src/index.ts:109]: This will both log this error and the one below, and fall through to the next iteration of the loop. I don't think that's what you intended?

**Review by Arachnid — CHANGES_REQUESTED** [review]

File: packages/ethers-ccip-read-provider/src/index.ts (hunk 1 above)
Comment (mdtanrikulu) [reply packages/ethers-ccip-read-provider/src/index.ts:109]: right, it's not what I was intended. updated now.

**Review by Arachnid — APPROVED** [review]
